name: herbixpvp
main: com.github.herbix.pvpplugin.PvpPlugin
version: 0.3.1.46
commands:
  red:
    description: Change my team to red.
    usage: /<command>
  blue:
    description: Change my team to blue.
    usage: /<command>
  pvpstart:
    description: Start pvp game.
    usage: /<command>
    permission: op
    permission-message: You don't have <permission>
  pvpstop:
    description: Stop pvp game.
    usage: /<command>
    permission: op
    permission-message: You don't have <permission>